import type {
  Backend,
  Config,
  ConfigUser,
  Paginated,
  PanelAdmin,
  Subscription,
} from "../domain/types";
import type { AdminRole } from "../index";

/**
 * Repository interfaces — the seam between the domain and storage.
 *
 * `D1RepositoryFactory` (Workers) is implemented first; a Node SQLite
 * implementation with the same interfaces enables self-hosting without
 * touching routes or services (docs/architecture.md → portability).
 *
 * All timestamps are unix seconds. All ids are TEXT UUIDs generated by
 * the caller, never by the database.
 */

export interface UserRepository {
  list(params: {
    search?: string;
    status?: ConfigUser["status"];
    page: number;
    perPage: number;
  }): Promise<Paginated<ConfigUser>>;
  getById(id: string): Promise<ConfigUser | null>;
  getByUsername(username: string): Promise<ConfigUser | null>;
  create(user: Omit<ConfigUser, "createdAt" | "updatedAt">): Promise<ConfigUser>;
  update(
    id: string,
    patch: Partial<Omit<ConfigUser, "id" | "createdAt">>,
  ): Promise<ConfigUser>;
  delete(id: string): Promise<void>;
}

export interface BackendRepository {
  list(params?: { status?: Backend["status"] }): Promise<Backend[]>;
  getById(id: string): Promise<Backend | null>;
  getByName(name: string): Promise<Backend | null>;
  create(backend: Omit<Backend, "createdAt" | "updatedAt">): Promise<Backend>;
  update(
    id: string,
    patch: Partial<Omit<Backend, "id" | "createdAt">>,
  ): Promise<Backend>;
  delete(id: string): Promise<void>;
}

export interface ConfigRepository {
  list(params: {
    search?: string;
    protocol?: Config["protocol"];
    userId?: string;
    backendId?: string;
    page: number;
    perPage: number;
  }): Promise<Paginated<Config>>;
  getById(id: string): Promise<Config | null>;
  /** Idempotent upsert keyed by UNIQUE(user_id, backend_id). */
  upsert(config: Omit<Config, "createdAt" | "updatedAt">): Promise<Config>;
  delete(id: string): Promise<void>;
  deleteByUser(userId: string): Promise<void>;
  deleteByBackend(backendId: string): Promise<void>;
}

export interface SubscriptionRepository {
  list(params?: { userId?: string }): Promise<Subscription[]>;
  getById(id: string): Promise<Subscription | null>;
  getByToken(token: string): Promise<Subscription | null>;
  create(
    subscription: Omit<Subscription, "createdAt" | "updatedAt">,
  ): Promise<Subscription>;
  update(
    id: string,
    patch: Partial<
      Omit<Subscription, "id" | "userId" | "token" | "createdAt">
    >,
  ): Promise<Subscription>;
  delete(id: string): Promise<void>;
  deleteByUser(userId: string): Promise<void>;
  recordAccess(token: string): Promise<void>;
}

/**
 * Admin row including the password hash. Internal to the auth flow —
 * never serialize this directly to API responses.
 */
export type AdminWithHash = PanelAdmin & { passwordHash: string };

export interface AdminRepository {
  list(): Promise<PanelAdmin[]>;
  /** Includes passwordHash — internal, never serialize directly. */
  getById(id: string): Promise<AdminWithHash | null>;
  /** Includes passwordHash — internal, never serialize directly. */
  getByUsername(username: string): Promise<AdminWithHash | null>;
  create(
    admin: Omit<PanelAdmin, "createdAt" | "updatedAt"> & { passwordHash: string },
  ): Promise<PanelAdmin>;
  update(
    id: string,
    patch: Partial<Omit<PanelAdmin, "id" | "createdAt">> & { passwordHash?: string },
  ): Promise<PanelAdmin>;
  delete(id: string): Promise<void>;
  count(): Promise<number>;
  countOwnersExcluding(id: string): Promise<number>;
}

/**
 * Bearer-token sessions. Rows are keyed by SHA-256(token) (UNIQUE), so
 * logout revokes exactly the presented token and password change revokes
 * everything belonging to the admin.
 */
export interface SessionRepository {
  create(session: {
    id: string;
    adminId: string;
    tokenHash: string;
    expiresAt: number;
    createdAt: number;
  }): Promise<void>;
  /** Single round-trip auth lookup: session row + owning admin. */
  getAuthByTokenHash(tokenHash: string): Promise<{
    expiresAt: number;
    admin: { id: string; username: string; role: AdminRole; isActive: boolean };
  } | null>;
  deleteByTokenHash(tokenHash: string): Promise<void>;
  deleteByAdmin(adminId: string): Promise<void>;
  deleteExpired(now: number): Promise<void>;
}

export interface SettingsRepository {
  getAll(): Promise<Record<string, unknown>>;
  get<T>(key: string): Promise<T | null>;
  set(key: string, value: unknown): Promise<void>;
}

export interface StatsRepository {
  overview(): Promise<{
    totals: {
      users: number;
      activeUsers: number;
      configs: number;
      backends: { total: number; active: number };
      subscriptions: { total: number; active: number };
    };
    configsPerDay: { date: string; count: number }[];
    byProtocol: Record<Config["protocol"], number>;
  }>;
}

/** Bundle handed to services via DI (env.DB in Workers, sqlite in Node). */
export interface RepositoryBundle {
  users: UserRepository;
  backends: BackendRepository;
  configs: ConfigRepository;
  subscriptions: SubscriptionRepository;
  admins: AdminRepository;
  settings: SettingsRepository;
  sessions: SessionRepository;
  stats: StatsRepository;
}
